// autodrive-data.js — Static Autodrive configuration data (placement profiles +
// templates). Split from autodrive-engine.js so the engine stays focused on
// logic; both files are pure ESM and covered by the engine tests.

/** @typedef {"soft_external"|"deep_pressure"|"dual"|"perineum_combo"|"insertable"|"loops_ab_penis"|"loops_ab_glans_hot"} PlacementProfile */
/** @typedef {"both"|"alt"|"aLead"|"bLead"} ChannelMode */
/**
 * Placement profiles map common ESTIM body applications → sensation plane + caps.
 * Research-aligned (below-waist only; pads softer; loops/glans hotter; insertables careful).
 */
export const PLACEMENT_PROFILES = Object.freeze({
  soft_external: {
    id: "soft_external",
    label: "Pads extern",
    freqBias: -15,
    dutyScale: 1.08,
    strengthCap: 0.92,
    preferredChannelMode: "both",
    description: "Flächige Pads — weich, Einsteiger-freundlich",
    bodySites: "Haftpads auf intakter Haut unterhalb der Taille",
    setupMale:
      "z. B. Pad Perineum + Pad Schaftbasis, oder zwei Pads seitlich am Schaft (nicht über dem Herzen)",
    setupFemale:
      "z. B. Pads beidseits der Labien / innere Oberschenkel nahe dem Schritt — nicht direkt auf die Klitoris-Glans",
    sensation: "Weich, flächig, eher „throb“ bei niedriger Wire-Freq",
    recommendedAbRole: "sync",
    recommendedFocus: "both",
    tips: [
      "Große Pad-Fläche = weicher; kleine Pads = punktuell schärfer",
      "Guter Kontakt / leitfähiges Gel bei schlechter Haftung",
      "Soft-Limits erst nach Kalibrierung anheben",
    ],
  },
  deep_pressure: {
    id: "deep_pressure",
    label: "Loops 1-Kanal",
    freqBias: 12,
    dutyScale: 0.9,
    strengthCap: 0.82,
    preferredChannelMode: "both",
    description: "Zwei Loops auf einem Kanal: Basis↔Glans — fokussiert",
    bodySites: "Conductive Loops / Cockrings auf einem Coyote-Kanal (A oder B)",
    setupMale:
      "Genau ein Kanal (A oder B): Loop an der Basis + Loop unter der Eichel — Strom entlang des Schafts. Anderer Kanal ungenutzt.",
    setupFemale:
      "Weniger typisch — eher Pads/Insertables; optional Ringe an Oberschenkel-Falten nur mit Vorsicht",
    sensation: "Fokussiert, oft „schneidender“ bei höherer Wire-Freq — Cap bewusst niedriger",
    recommendedAbRole: "sync",
    recommendedFocus: "A",
    tips: [
      "Im Setup „2 Loops · 1 Kanal“ wählen und A oder B stecken",
      "Eichel-nah = empfindlich: Kalibrierung und „Zu stark“ nutzen",
      "Loops nicht zu eng; Haut nicht abschnüren",
      "Für Stereo A+B am Penis → „4 Kontakte · A und B getrennt“",
    ],
  },
  /** Primary profile for dual-channel penis loops only (user's main setup). */
  loops_ab_penis: {
    id: "loops_ab_penis",
    label: "Loops A+B Penis",
    freqBias: 6,
    dutyScale: 0.96,
    strengthCap: 0.86,
    preferredChannelMode: "alt",
    description: "Nur Penis: Kanal A + B je eigener Loop-Kreis",
    bodySites: "4 Kontakte am Schaft / Eichel-Bereich (2 Kreise, A und B)",
    setupMale:
      "A: Loop Basis ↔ Loop Mitte Schaft · B: Loop Mitte/Corona ↔ Loop unter Eichel. " +
      "Alternativ A Basis↔Corona und B Corona↔Glans (getrennte Kreise, kein Shared-Return über den Körperstamm).",
    setupFemale: "Primär für Penis-Loops gedacht — für Vulva eher Pads dual nutzen",
    sensation:
      "Stereo am Schaft: A eher „Grundlage/Rhythmus“, B eher „Spitze/Detail“ — Alternate und A/B-Rollen wirken stark",
    recommendedAbRole: "aRhythm_bSteady",
    recommendedFocus: "both",
    tips: [
      "B/Glans oft empfindlicher → Soft-Limit B etwas niedriger oder Sensitivität sanft",
      "Empfohlen: A Rhythmus · B Steady (Basis pulsiert, Spitze hält)",
      "Loops gleichmäßig feucht/leitend; Abstand der Ringe = Sensation ändern",
      "Kalibrierung mit beiden Kanälen; bei scharfem Glans „Zu stark“ tippen",
    ],
  },
  loops_ab_glans_hot: {
    id: "loops_ab_glans_hot",
    label: "Loops A+B · Glans hot",
    freqBias: 14,
    dutyScale: 0.88,
    strengthCap: 0.8,
    preferredChannelMode: "aLead",
    description: "A+B am Penis, B/Glans führend — intensiver",
    bodySites: "Wie Loops A+B, aber stärkerer Fokus auf den glans-nahen Kreis",
    setupMale:
      "A: Basis ↔ untere Schaftmitte (breiterer, weicherer Kreis) · B: Corona ↔ unter Eichel (enger, heißer Kreis)",
    setupFemale: "Nicht typisch — siehe Loops A+B / Pads",
    sensation: "Mehr „edge“ und Stechen an der Spitze — niedrigeres Cap, A führt oft weicher",
    recommendedAbRole: "aSteady_bRhythm",
    recommendedFocus: "both",
    tips: [
      "Soft-Limit B strenger setzen als A",
      "A Steady · B Rhythmus: Spitze bekommt Pattern, Basis hält",
      "Bei Brennen: Placement zurück auf „Loops A+B Penis“ oder Sync",
    ],
  },
  dual: {
    id: "dual",
    label: "Dual A/B Stereo",
    freqBias: 0,
    dutyScale: 1,
    strengthCap: 0.93,
    preferredChannelMode: "alt",
    description: "Zwei Kreise — nicht nur Penis (z. B. Schaft + Perineum/Plug)",
    bodySites:
      "Kanal A und B an unterschiedlichen Stellen (kein gemeinsamer Elektroden-Pfad über die Brust)",
    setupMale:
      "z. B. A: Perineum↔Basis · B: Basis↔Glans — oder A Schaft, B bipolarer Plug (getrennte Kreise)",
    setupFemale: "z. B. A: Labien-Seiten · B: bipolarer Vaginal-Probe — Kreise nicht kreuzen",
    sensation: "Räumlich / abwechselnd; gut mit A/B-Rollen „Rhythmus + Steady“",
    recommendedAbRole: "aRhythm_bSteady",
    recommendedFocus: "both",
    tips: [
      "Jeden Kanal als eigenen Stromkreis behandeln",
      "Nur Penis A+B → besser „Loops A+B Penis“",
      "Fokus A/B im UI, wenn ein Kanal deutlich empfindlicher ist",
    ],
  },
  perineum_combo: {
    id: "perineum_combo",
    label: "Perineum + Basis",
    freqBias: 4,
    dutyScale: 0.95,
    strengthCap: 0.88,
    preferredChannelMode: "both",
    description: "Pad Perineum + Loop/Pad Basis — tiefer, beckenboden-nah",
    bodySites: "Perineum (zwischen Anus und Genitalien) + Schaftbasis / Pubis",
    setupMale:
      "Pad mittig auf dem Perineum + Loop/Pad an der Penisbasis — Strom durch den Beckenboden",
    setupFemale: "Pad Perineum + zweites Pad unterer Schamhügel / innere Oberschenkel-Nähe",
    sensation: "Tiefer, „innerer“ Druck; oft prostate-/beckenboden-nah ohne Insertable",
    recommendedAbRole: "sync",
    recommendedFocus: "both",
    tips: [
      "Haare kürzen / Gel für gleichmäßigen Kontakt am Perineum",
      "Nicht zu nah am Anus bei frischen Wunden/Hämorrhoiden",
      "Mittlere Templates (Klassisch, Deny) passen gut",
    ],
  },
  insertable: {
    id: "insertable",
    label: "Insertable bipolar",
    freqBias: -8,
    dutyScale: 0.88,
    strengthCap: 0.78,
    preferredChannelMode: "both",
    description: "Bipolarer Plug/Probe — lokal, konservatives Cap",
    bodySites: "Körpergerechte ESTIM-Insertables (anal/vaginal), bipolar = Strom im Toy",
    setupMale: "Bipolarer Anal-Plug (± im Toy); optional zweiter Kanal separat mit Loop am Schaft",
    setupFemale: "Bipolarer Vaginal-Probe oder Anal-Plug — nur ESTIM-geeignetes Material",
    sensation: "Sehr lokal; kann schnell intensiv wirken → niedriges Cap + sanfte Freq",
    recommendedAbRole: "sync",
    recommendedFocus: "A",
    tips: [
      "Nur toys die für Elektro-Play gebaut sind; reichlich leitfähiges Gleitgel",
      "Nie mit Strom ein-/ausstecken — Strength 0 / Soft-Stop zuerst",
      "Kalibrierung nicht überspringen; „Zu stark“ früh tippen",
    ],
  },
});

export const AUTODRIVE_TEMPLATES = Object.freeze({
  quick_finish: {
    id: "quick_finish",
    label: "Schnell",
    description: "5 Min, direkt zum Höhepunkt",
    targetDurationMin: 5,
    goal: "direct",
    sensitivity: "medium",
    edgeCount: 0,
    maxSessionIntensityFactor: 0.95,
    allowClimaxPatterns: true,
    aggression: 1.15,
  },
  classic: {
    id: "classic",
    label: "Klassisch",
    description: "12 Min, 2 Edges, dann Push",
    targetDurationMin: 12,
    goal: "edge_then_release",
    sensitivity: "medium",
    edgeCount: 2,
    maxSessionIntensityFactor: 0.95,
    allowClimaxPatterns: true,
    aggression: 1.0,
  },
  long_tease: {
    id: "long_tease",
    label: "Langer Tease",
    description: "20 Min, 4 Edges, sanft steigend",
    targetDurationMin: 20,
    goal: "edge_ladder",
    sensitivity: "gentle",
    edgeCount: 4,
    maxSessionIntensityFactor: 0.9,
    allowClimaxPatterns: false,
    aggression: 0.85,
  },
  intense: {
    id: "intense",
    label: "Intensiv",
    description: "10 Min, harter Drive, Cap 85%",
    targetDurationMin: 10,
    goal: "direct",
    sensitivity: "intense",
    edgeCount: 1,
    maxSessionIntensityFactor: 0.85,
    allowClimaxPatterns: true,
    aggression: 1.25,
  },
  marathon: {
    id: "marathon",
    label: "Marathon",
    description: "30 Min, 6 Edges, Ausdauer",
    targetDurationMin: 30,
    goal: "edge_ladder",
    sensitivity: "gentle",
    edgeCount: 6,
    maxSessionIntensityFactor: 0.88,
    allowClimaxPatterns: true,
    aggression: 0.75,
  },
  turbo: {
    id: "turbo",
    label: "Turbo",
    description: "3 Min, aggressiv, wenig Tease",
    targetDurationMin: 3,
    goal: "direct",
    sensitivity: "intense",
    edgeCount: 0,
    maxSessionIntensityFactor: 0.98,
    allowClimaxPatterns: true,
    aggression: 1.4,
  },
  deny: {
    id: "deny",
    label: "Deny & Release",
    description: "Fast abspritzen → Deny → harter Push",
    targetDurationMin: 15,
    goal: "deny_then_release",
    sensitivity: "medium",
    edgeCount: 3,
    maxSessionIntensityFactor: 0.92,
    allowClimaxPatterns: true,
    aggression: 1.1,
  },
  // --- Penis dual-loop presets (Kanal A + B nur am Schaft/Glans) ---
  loops_classic: {
    id: "loops_classic",
    label: "Loops A+B · Klassisch",
    description: "12 Min · 2 Edges · A Rhythmus B Steady",
    targetDurationMin: 12,
    goal: "edge_then_release",
    sensitivity: "medium",
    edgeCount: 2,
    maxSessionIntensityFactor: 0.9,
    allowClimaxPatterns: true,
    aggression: 1.0,
    placement: "loops_ab_penis",
    abRole: "aRhythm_bSteady",
    channelFocus: "both",
    group: "loops",
  },
  loops_tease: {
    id: "loops_tease",
    label: "Loops A+B · Tease",
    description: "18 Min · 4 Edges · sanft, lange Leiter",
    targetDurationMin: 18,
    goal: "edge_ladder",
    sensitivity: "gentle",
    edgeCount: 4,
    maxSessionIntensityFactor: 0.86,
    allowClimaxPatterns: false,
    aggression: 0.88,
    placement: "loops_ab_penis",
    abRole: "aRhythm_bSteady",
    channelFocus: "both",
    group: "loops",
  },
  loops_edge: {
    id: "loops_edge",
    label: "Loops A+B · Edge",
    description: "15 Min · Deny-Style · Glans vorsichtiger Cap",
    targetDurationMin: 15,
    goal: "deny_then_release",
    sensitivity: "medium",
    edgeCount: 3,
    maxSessionIntensityFactor: 0.88,
    allowClimaxPatterns: true,
    aggression: 1.05,
    placement: "loops_ab_penis",
    abRole: "aSteady_bRhythm",
    channelFocus: "both",
    group: "loops",
  },
  loops_glans: {
    id: "loops_glans",
    label: "Loops A+B · Glans-Hot",
    description: "10 Min · B/Spitze führend · niedrigeres Cap",
    targetDurationMin: 10,
    goal: "edge_then_release",
    sensitivity: "gentle",
    edgeCount: 2,
    maxSessionIntensityFactor: 0.84,
    allowClimaxPatterns: true,
    aggression: 1.08,
    placement: "loops_ab_glans_hot",
    abRole: "aSteady_bRhythm",
    channelFocus: "both",
    group: "loops",
  },
  loops_rush: {
    id: "loops_rush",
    label: "Loops A+B · Rush",
    description: "6 Min · direkter Push · sync beide Loops",
    targetDurationMin: 6,
    goal: "direct",
    sensitivity: "medium",
    edgeCount: 0,
    maxSessionIntensityFactor: 0.9,
    allowClimaxPatterns: true,
    aggression: 1.22,
    placement: "loops_ab_penis",
    abRole: "sync",
    channelFocus: "both",
    group: "loops",
    climaxPriority: true,
    // v6.1: kurze Kurve + Push-Retry für den schnellen Finish-Pfad
    climaxCurve: "kurz",
    pushRetry: true,
  },
  /** Climax-first: 1 edge → long multi-wave push, both channels full */
  finish_loops: {
    id: "finish_loops",
    label: "★ Abspritzen · Loops",
    description: "14 Min · 1 Edge · langer Push · A+B Sync",
    targetDurationMin: 14,
    goal: "edge_then_release",
    sensitivity: "medium",
    edgeCount: 1,
    maxSessionIntensityFactor: 0.94,
    allowClimaxPatterns: true,
    aggression: 1.2,
    placement: "loops_ab_penis",
    abRole: "sync",
    channelFocus: "both",
    group: "loops",
    climaxPriority: true,
    // v6.1: accelerating climax curve + push-retry (unmarked push → re-push)
    climaxCurve: "standard",
    pushRetry: true,
  },
  finish_glans: {
    id: "finish_glans",
    label: "★ Abspritzen · Glans",
    description: "12 Min · 1 Edge · B-Spitze · Balance schonend",
    targetDurationMin: 12,
    goal: "edge_then_release",
    sensitivity: "gentle",
    edgeCount: 1,
    maxSessionIntensityFactor: 0.9,
    allowClimaxPatterns: true,
    aggression: 1.12,
    placement: "loops_ab_glans_hot",
    abRole: "aSteady_bRhythm",
    channelFocus: "both",
    group: "loops",
    climaxPriority: true,
    climaxCurve: "standard",
    pushRetry: true,
  },
  finish_pads: {
    id: "finish_pads",
    label: "★ Abspritzen · Pads",
    description: "12 Min · 1 Edge · weiche Fläche · voller Push",
    targetDurationMin: 12,
    goal: "edge_then_release",
    sensitivity: "medium",
    edgeCount: 1,
    maxSessionIntensityFactor: 0.96,
    allowClimaxPatterns: true,
    aggression: 1.15,
    placement: "soft_external",
    abRole: "sync",
    channelFocus: "both",
    group: "finish",
    climaxPriority: true,
    climaxCurve: "standard",
    pushRetry: true,
  },
  /** Two loops on one Coyote channel (base ↔ glans) */
  loops_single: {
    id: "loops_single",
    label: "Loops 1-Kanal · Klassisch",
    description: "12 Min · 2 Edges · nur ein Kanal (A oder B)",
    targetDurationMin: 12,
    goal: "edge_then_release",
    sensitivity: "medium",
    edgeCount: 2,
    maxSessionIntensityFactor: 0.88,
    allowClimaxPatterns: true,
    aggression: 1.05,
    placement: "deep_pressure",
    wiringMode: "single_channel_2",
    electrodeKind: "loops",
    abRole: "sync",
    channelFocus: "A",
    group: "loops_single",
  },
  finish_loops_single: {
    id: "finish_loops_single",
    label: "★ Abspritzen · 1-Kanal",
    description: "12 Min · 1 Edge · 2 Loops auf einem Kanal",
    targetDurationMin: 12,
    goal: "edge_then_release",
    sensitivity: "medium",
    edgeCount: 1,
    maxSessionIntensityFactor: 0.9,
    allowClimaxPatterns: true,
    aggression: 1.18,
    placement: "deep_pressure",
    wiringMode: "single_channel_2",
    electrodeKind: "loops",
    abRole: "sync",
    channelFocus: "A",
    group: "loops_single",
    climaxPriority: true,
    climaxCurve: "standard",
    pushRetry: true,
  },
  // F1: Climax-Fabrik — programmed edging loops, full frequency band.
  climax_factory: {
    id: "climax_factory",
    label: "⚙️ Climax-Fabrik",
    description: "18 Min · 2 Edges mit programmierten Loop-Zyklen · 2 Climaxes",
    targetDurationMin: 18,
    goal: "edge_then_release",
    sensitivity: "medium",
    edgeCount: 2,
    maxSessionIntensityFactor: 0.95,
    allowClimaxPatterns: true,
    aggression: 1.05,
    climaxPriority: true,
    edgeLoops: true,
    edgeCycleTarget: 2,
    freqFullBand: true,
    climaxTarget: 2,
    group: "climax",
    climaxCurve: "standard",
    pushRetry: true,
  },
  // F1: HFO — hands-free orgasm program (long slow build, full band, gentle finish).
  hfo: {
    id: "hfo",
    label: "🌀 HFO (Hände frei)",
    description: "25 Min · langsamer Aufbau · volle Frequenz-Bandbreite · sanfter Finish",
    targetDurationMin: 25,
    goal: "hfo",
    sensitivity: "medium",
    edgeCount: 1,
    maxSessionIntensityFactor: 0.9,
    allowClimaxPatterns: true,
    aggression: 0.9,
    climaxPriority: true,
    edgeLoops: true,
    edgeCycleTarget: 3,
    freqFullBand: true,
    climaxTarget: 1,
    group: "climax",
    climaxCurve: "verzoegert",
    pushRetry: true,
  },
});
